lib/payola.rb
spec/payola_spec.rb

e739e16 introduced a regression where the Payola user has to `#call`
the result of the public and private keys. This commit instead wraps
the env in a wrapper object that properly evaluates `to_s` and `==`.
Fixes #71

Don't require callers to #call the keys

---

app/services/payola/start_subscription.rb

This fixes an issue where subscriptions would fail if they had a setup fee, due to the missing secret_key.
Because of this issue, #71, and #73, we should probably cut a 1.2.4 gem. At least for me, the published 1.2.3 is pretty much unusable.

Fix subscriptions with setup fees.

---

app/assets/javascripts/payola/subscription_form_onestep.js
app/assets/javascripts/payola/subscription_form_twostep.js

The `error` function for `$.ajax` just receives a `jqXHR` object
instead of parsed data. We return an error code in cases where the
card has been declined, which triggers the error handler instead of
the success handler. So we need a dedicated error handler instead
of trying to overload the success handler to handle all the cases.

Fix error handling for subscriptions.

---

app/models/concerns/payola/plan.rb

Namespaced models resolve to invalid classes :
Some::Model.to_s.underscore => some/model :-1: 
Some::Model.to_s.underscore. parameterize => some-model :+1:

Support for namespaced models

---

app/services/payola/charge_card.rb
app/services/payola/invoice_behavior.rb
app/services/payola/start_subscription.rb
app/services/payola/update_card.rb
lib/payola.rb
payola.gemspec
spec/models/payola/subscription_spec.rb
spec/services/payola/invoice_failed_spec.rb
spec/services/payola/invoice_paid_spec.rb

Note that this *forces* API version 2015-02-18. If you have non-Payola
code using the Stripe gem you will have to update it.
Fixes #93
Fixes #96

Support API version 2015-02-18

---

app/assets/javascripts/payola/subscription_checkout_button.js
app/views/payola/subscriptions/_checkout.html.erb

Similar to when creating a custom form, allow the checkout button flow to accept (and respect) a custom URL to post data to after async Stripe communication has finished

Allow custom URL to be used with the subscription checkout button

---

app/services/payola/start_subscription.rb
spec/services/payola/start_subscription_spec.rb

If a customer has been deleted within Stripe for some reason, attempting to access any attributes (other than `id` or `deleted`) with throw an exception.

Ensure the Stripe::Customer hasn't been deleted

---

app/views/payola/subscriptions/_cancel.html.erb

* Fix a bug where the `class` and `disabled` attributes weren't being properly set on the cancel subscription submit tag
* Allow a custom url to be passed to the cancel subscription partial via a `url` local.
* Render cancel subscription button the with the same HTML structure as the checkout button

Cancel subscription button

---

db/migrate/20141001170138_create_payola_sales.rb
db/migrate/20141002203725_add_stripe_customer_id_to_sale.rb
db/migrate/20141029135848_add_owner_to_payola_sale.rb
db/migrate/20141107025420_add_guid_to_payola_subscriptions.rb
spec/services/payola/change_subscription_quantity_spec.rb

mysql `utf8mb4` encoding (4 byte UTF-8) supports a max index length of `767` bytes. This means that a string column that will have an index has two options:
* limit the max length of the column to `191` chars (`191 * 4 = 764`)
* use a prefix index (index only the first part of the string), and ensure the number of bytes indexes is less than the max
In this PR, I've opted to take the first approach. I thought about checking the encoding on the database connection, and only limiting the length of the columns if it was set to `utf8mb4`, but I figured that could potentially just cause issues if only one database limited the column lengths.
While testing this change, I also fixed a spec that was failing when running using mysql.

Mysql utf8 indices

---

app/services/payola/invoice_behavior.rb

This occurred when the card was accepted, but was declined when the charge was made using card 4000000000000341

Fix payment failed when card is declined.

---

app/assets/javascripts/payola/checkout_button.js
app/views/payola/transactions/_checkout.html.erb

Added bitcoin option to checkout.js. Won't work unless the amount is USD. Stripe will show the bitcoin option greyed out when the currency is different from USD.
Related to issue #124 still checking about allowing two-step payments.

Added bitcoin option to checkout.js

---

app/services/payola/cancel_subscription.rb

This change allows us to pass the `at_period_end` argument to Stripe that signifies that the subscription is to remain active until the end of the subscription period.
```ruby
Payola::CancelSubscription.call(subscription, { at_period_end: true })
```
I'm skipping over the `subscription.cancel!` call if this argument exists, so in order to cancel the subscription the user must monitor for the `customer.subscription.deleted` webhook that Stripe will send upon subscription cancelation:
```ruby
config.subscribe 'customer.subscription.deleted' do |event|
subscription = Subscription.find_by(stripe_id: event.data.object.id)
subscription.cancel!
end 
```
Please let me know if this is kosher or if you'd like this handled in a different manner.  Thanks!

Support for canceling subscription at period end

---

app/services/payola/change_subscription_plan.rb
spec/services/payola/change_subscription_plan_spec.rb

Allows coupon to be applied to changing subscription, and turns off prorating in that scenario per Stripe instructions.

allowing coupons on changing subscriptions per Stripe instructions

---

app/assets/javascripts/payola/form.js
app/assets/javascripts/payola/subscription_checkout_button.js
app/assets/javascripts/payola/subscription_form_onestep.js
app/assets/javascripts/payola/subscription_form_twostep.js

Triggering an `error` event will make it easier to customize responses to stripe errors.
In my case I've combined user registration and payment into a single form and I need to remove an `is-submitting` class on the form on error. Happy to write tests for these changes, unfortunately I don't see any js specs in the repo.

Trigger error event on form when an error occurs

---

app/models/payola/subscription.rb
app/services/payola/create_subscription.rb
app/services/payola/start_subscription.rb
spec/factories/payola_subscriptions.rb
spec/models/payola/subscription_spec.rb

This change adds support for the trial_end attribute when creating a subscription, and also changes the stripeToken value to be optional.
This former allows creation of a subscription with a trial period, and the later allows creation of a subscription without needing a user's credit card information if the user already exists in Stripe (for administrative purposes, or for future purchases with Stripe who will use the customer's attached card as the payment source).
I put an exception in place if the stripeToken value is not passed and the customer does not exist in Stripe.
Creating a subscription in this manner would be done like:
```ruby
subscription_params = {
plan: subscription_plan,
stripeEmail: user_email,
quantity: 1,
trial_end: 7.days.from_now
} …
```

Support for subscription creation with trial_end and optional stripeToken

---

app/models/concerns/payola/plan.rb
lib/payola.rb
spec/concerns/plan_spec.rb
spec/payola_spec.rb

Make this default to true for backwards compatibility.
This is necessary if you create plans in your test suite (as opposed to only using fixtures).
We could also set the template initializer to include this, possibly commented out:
```ruby
if Rails.env.test?
config.create_stripe_plans = false
end
```
What do you think? Unexpectedly creating the plans in Stripe is definitely a bit of a gotcha at present.

Add config option to determine whether to create plans in Stripe

---

app/models/payola/subscription.rb

Don't assume it's defined - call `#respond_to?` first to check the attribute exists in the same way as we do for other optional attributes in the CreatePlan service.
Otherwise anyone that isn't using this attribute will hit an exception in the `conditional_stripe_token` validation.

Allow Plan#trial_period_days attribute to remain optional

---

app/assets/javascripts/payola/checkout_button.js
app/assets/javascripts/payola/form.js
app/assets/javascripts/payola/subscription_checkout_button.js
app/assets/javascripts/payola/subscription_form_onestep.js
app/assets/javascripts/payola/subscription_form_register.js
app/assets/javascripts/payola/subscription_form_twostep.js
app/views/payola/transactions/_form.html.erb

Annoyingly, jQuery doesn't parse the response as JSON if the status code
is an error (http://stackoverflow.com/q/12310702/117104), even though
the server response's Content-Type is correctly set to application/json.
So in our XHR error handlers, xhr.responseJSON was always undefined.
Manually parse the responseText as JSON using jQuery.parseJSON().
Note that this won't behave correctly if the server doesn't return JSON
(eg. if there's a 500 error for some reason and it returns an HTML error
page or something, or there's a 404 and it renders 'nothing').It would
be good to handle those cases. I think we'd want to DRY up the error
handlers first though as it's a bit verbose to handle all these cases
correctly.

Fix jQuery XHR JSON error handling

---

spec/concerns/plan_spec.rb

This caused the test suite failures I was seeing in #161 (there may be others, but after fixing this issue I couldn't find another test ordering seed which caused the suite to fail).
Some tests currently expect plans to be implicitly created in Stripe. Depending on the order that the suite ran in, `Payola.create_stripe_plans` could be set to false when these examples ran, which would prevent plans from being created in Stripe. This caused failures.
For now, make sure we set `Payola.create_stripe_plans` back to the default of `true`, so that tests that depend on this behaviour will keep working whatever order the suite is run in.

Ensure Payola.create_stripe_plans global gets set back to true

---

app/views/payola/subscriptions/_checkout.html.erb

Previously, if you rendered more than one payola/subscriptions/checkout partial in a single page, Stripe Checkout's JS and CSS files will be included multiple times. This doesn't seem to break anything, but it would be better if it didn't happen.
Add `include_stripe_checkout_assets` option when rendering the partial, which defaults to true for backwards compatibility.
This seems a bit dirty. I think it would be better to instruct people to include the Checkout JS and CSS in their own application layout (or wherever they need to) rather than having an option for the partial, but we can't change this without a major version bump as that would break backwards compatibility in a big way.

Make outputting Stripe checkout JS and CSS optional

---

app/controllers/payola/subscriptions_controller.rb
app/views/payola/subscriptions/_cancel.html.erb
spec/controllers/payola/subscriptions_controller_spec.rb

We already have support in `CancelSubscription` for the `at_period_end` param, but you had to call that service manually to be able to pass that argument through.
Add support for an `at_period_end` param in the stock `subscriptions/_cancel` partial, and pass it through to the `CancelSubscription` service from the `SubscriptionsController#destroy` method.

Pass at_period_end param to CancelSubscription, support it in subscriptions/_cancel partial

---

app/services/payola/subscription_deleted.rb
lib/payola/engine.rb
spec/services/payola/subscription_deleted_spec.rb

The customer's subscription can be deleted if they progress through the dunning cycle, and you have configured your account to cancel their subscription after their final failure to pay (see https://stripe.com/docs/guides/subscriptions#payment-failures for details).
It can also be deleted if you manually cancel their subscription via the Stripe Dashboard.
In both cases we should listen for Stripe's customer.subscription.deleted webhook and cancel the Payola::Subscription as we do if the customer chooses to end their subscription via the CancelSubscription service.
Otherwise, their Payola::Subscription only ends up in the canceled state if the customer has explicitly initiated canceling it themselves.

Listen for customer.subscription.deleted webhooks and cancel the associated subscription

---

app/controllers/payola/cards_controller.rb
app/controllers/payola/customers_controller.rb
app/services/payola/create_card.rb
app/services/payola/destroy_card.rb
app/services/payola/update_customer.rb
config/routes.rb
spec/controllers/payola/cards_controller_spec.rb
spec/controllers/payola/customers_controller_spec.rb
spec/services/payola/create_card_spec.rb
spec/services/payola/destroy_card_spec.rb
spec/services/payola/update_customer_spec.rb

This change adds two features:
- The ability to add and remove credit cards from a customer's source list
- The ability to update a customer's attributes
Currently, I am only allowing the customer `default_source` attribute to be passed, but more can be added by editing the `customer_params` method in `CustomerController`.
I also have added logic to prevent duplicate cards from being created.
Similar to the `SubscriptionController`, I have added support for a method in `ApplicationController` called `payola_can_modify_customer?` that can prevent unauthorized users from modifying others' customer objects or cards.  The method can be implemented in `ApplicationController` like:
```ruby
def payola_can_modify_customer?(stripe_customer_id)
current_user.stripe_customer_id == stripe_customer_id …
```

Functionality to manage multiple cards and update customer attributes

---

app/controllers/payola/cards_controller.rb
app/controllers/payola/customers_controller.rb
spec/controllers/payola/cards_controller_spec.rb
spec/controllers/payola/customers_controller_spec.rb

This is a small change that adds support for custom return paths after performing a card or customer action.
To use it, you can pass a location via `return_to` and it will return there rather than `:back`
It can be used like:
```ruby
= link_to "Make Primary Card", payola.update_customer_path(current_user.stripe_customer_id, 
"customer[default_source]" => card[:id]), return_to: after_primary_card_path(current_user)), 
method: :post
```

Support for custom return paths after customer/card actions

---

app/assets/javascripts/payola/subscription_checkout_button.js
app/models/payola/subscription.rb
app/services/payola/create_subscription.rb
app/services/payola/start_subscription.rb
app/views/payola/subscriptions/_checkout.html.erb
spec/controllers/payola/subscriptions_controller_spec.rb
spec/factories/payola_subscriptions.rb
spec/models/payola/subscription_spec.rb
spec/services/payola/start_subscription_spec.rb

At the moment, when you create a Subscription we look for an existing Subscription for the same owner, and if we find one, re-use the Stripe customer from the first subscription.
Extend this functionality by allowing you to specify the Stripe customer id to use on the subscription when creating it. For accounts that have made a purchase from you before this allows you to re-use the same Stripe customer when they choose to start a Subscription.
We probably want to handle re-using the Stripe customer from existing Sale records in the database in the same way.

Take optional stripe_customer_id to be used when creating a subscription

---

app/assets/javascripts/payola/subscription_checkout_button.js
app/views/payola/subscriptions/_checkout.html.erb

If you want to use the `payola/subscriptions/_checkout` partial, there wasn't a way to specify a coupon to be used with the subscription. Take coupon local variable in this partial and submit it to the server. The `SubscriptionsController` already handles this param correctly.

Take coupon local and submit it as a param in subscriptions/_checkout

---

app/services/payola/process_refund.rb
lib/generators/payola/templates/initializer.rb
spec/services/payola/process_refund_spec.rb

This change implements a `ProcessRefund` service to execute a refund with Stripe.
The existing webhook listener is still useful to listen for and sync refund events that happen on Stripe's side, but I needed a way to issue a refund locally.
Since creating a refund issues a `charge.refunded` callback, I've added the conditional `unless sale.refunded?` to the initializer template to prevent state change attempts against an already refunded sale.
This service can be called by:
```ruby
Payola::ProcessRefund.call(sale.guid) # returns the sale with any errors attached
or
Payola.queue!(Payola::ProcessRefund, sale.guid)
```

Allow sales to be refunded on the client side

---

app/services/payola/start_subscription.rb
spec/dummy/db/schema.rb
spec/services/payola/start_subscription_spec.rb

A minor fix to avoid the requirement of the StripeToken on StartSubscription for free plans (plans with amount == 0)

StartSubscription not longer requires StripeToken for free plans

---

app/services/payola/subscription_deleted.rb

The default webhook handler for 'customer.subscription.deleted' calls `SubscriptionDeleted`, which would previously always attempt to `#cancel!` the subscription.
However, it's possible (and likely) that the subscription has already been canceled. If the user cancels their subscription through your app, the subscription will be canceled by the `CancelSubscription` service, and later a webhook will arrive and call `SubscriptionDeleted`, which will attempt to cancel the subscription a second time.
Only attempt to cancel the subscription via the webhook if the subscription is in a state that can transition to canceled.

Only cancel subscription in SubscriptionDeleted if it can be canceled

---

app/assets/javascripts/payola/checkout_button.js
app/assets/javascripts/payola/form.js
app/assets/javascripts/payola/subscription_checkout_button.js
app/assets/javascripts/payola/subscription_form_onestep.js
app/assets/javascripts/payola/subscription_form_register.js
app/assets/javascripts/payola/subscription_form_twostep.js

A cursory examination of the JavaScript suggests that compatibility with Turbolinks can be achieved with little effort. Specifically:
1. There are several delegated event handlers in the JavaScript; these appear to be unnecessary
2. The various JavaScript initializations occur in jQuery document ready callbacks
This PR is an attempt to remove these preliminary obstacles to Turbolinks compatibility

Turbolinks compatibility

---

app/models/payola/subscription.rb
spec/models/payola/subscription_spec.rb

Payola `Subscription` stores plan [amount](https://github.com/peterkeen/payola/blob/879d078c98b0ce78e449fcfde7810add8af5f1e2/app/services/payola/create_subscription.rb#L29) & [currency](https://github.com/peterkeen/payola/blob/879d078c98b0ce78e449fcfde7810add8af5f1e2/app/services/payola/create_subscription.rb#L19) at creation by not [during update](https://github.com/peterkeen/payola/blob/879d078c98b0ce78e449fcfde7810add8af5f1e2/app/models/payola/subscription.rb#L96-L104).
This PR aims to synchronize `amount` & `currency` fields with Stripe subscription

Update subscription amount

---

app/services/payola/cancel_subscription.rb

I think this was probably accidentally committed while developing.
We don't want to set `Stripe.api_key` directly as this has global consequences. Use the pattern we use everywhere else of explicitly passing the API key to each API call.
Note that we are already explicitly passing the API key to our Stripe API calls in `CancelSubscription`.

Stop setting Stripe.api_key directly in CancelSubscription service

---

app/services/payola/cancel_subscription.rb
spec/services/payola/cancel_subscription_spec.rb

If `CancelSubscription` is called with `at_period_end: true`, also update the subscription to store that it will be canceled at the end of the billing period.
Previously, this attribute wouldn't be changed until the Payola subscription was synced with the associated Stripe subscription (ie. when a webhook arrived).
Also, add a test to assert that the Payola subscription isn't immediately canceled if the `at_period_end: true` option is used.

Update cancel_at_period_end in CancelSubscription service

---

spec/concerns/plan_spec.rb
spec/controllers/payola/subscriptions_controller_spec.rb
spec/controllers/payola/transactions_controller_spec.rb
spec/models/payola/sale_spec.rb
spec/payola_spec.rb
spec/services/payola/cancel_subscription_spec.rb
spec/spec_helper.rb
spec/worker_spec.rb

This PR fixes the following warnings from RSpec:
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<StandardError: Customer not found>. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /payola/spec/services/payola/cancel_subscription_spec.rb:20:in `block (3 levels) in <module:Payola>'.
```
```
Deprecation Warnings:
Requiring `rspec/autorun` when running …
```

Fix RSpec Warnings

---

app/assets/javascripts/payola/checkout_button.js
app/services/payola/create_sale.rb
app/services/payola/create_subscription.rb
app/views/payola/transactions/_checkout.html.erb

In the same vein as #170 by @nfm, this change allows a `stripe_customer_id` to be passed through and attached and processed on a sale object.  This allows a user to make multiple purchases without entering credit card information.
I did need to add ` Payola.secret_key` inside of `CreateSubscription` (which was missing from #170, maybe it's not needed if configured a certain way) as well as use it in `CreateSale`.

Take optional stripe_customer_id when creating a sale

---

app/views/payola/subscriptions/_checkout.html.erb
db/migrate/20151205004838_change_tax_percent_format_in_payola_subscriptions.rb
spec/dummy/db/schema.rb

Minor fix to change `tax_percent` from integer to decimal. Up to two decimal places as per Stripe's API documentation:
```
A positive decimal (with at most two decimal places) between 1 and 100.
This represents the percentage of the subscription invoice subtotal that will
be calculated and added as tax to the final amount each billing period. 
```

Convert tax_percent from integer to decimal (at most two decimal places)

---

app/assets/javascripts/payola/subscription_checkout_button.js

If I am overriding the [`form_url` in my `local_assigns`](https://github.com/peterkeen/payola/blob/fc613a41cfa61f2157a35305884f1dc59e5f9ba8/app/views/payola/subscriptions/_checkout.html.erb#L20) with a URL that isn't RESTful for plans, there is no way to know to which `Plan` the User is subscribing.
Adding the `plan_id` here doesn't hurt anything but may certainly come in handy for some others who might face this situation.

Send the plan_id along with the form submission

---

app/services/payola/start_subscription.rb
spec/services/payola/start_subscription_spec.rb

Since a free `Payola::Subscription` can be subscribed to without a customer payment source (`stripeToken`), any subsequent subscriptions will attempt to re-use the newly created `stripe_customer_id` that doesn't have a payment source associated with it (even if the customer has entered their CC info during the second subscription checkout phase.)
If we have an available `stripeToken` to use and the customer doesn't have a default payment source, it makes sense to assign it to the customer which will allow the transaction to succeed.

Set a customer's payment source if nil

---

app/assets/javascripts/payola/subscription_checkout_button.js

Previously the subscription options `coupon`, `tax_percent` and
`signed_custom_fields` were only added to the submitted form in the
Stripe token callback. If an existing Stripe custmer id was given these
options were ignored, meaning that a customer could not resubscribe
using a coupon code, for example.

Submit all subscription options for existing stripe customers

---

app/models/payola/subscription.rb
spec/models/payola/subscription_spec.rb

Stripe removes coupon codes from a subscription after their repeating
duration has elapsed. When this happens, or when the subscription is
changed for any other reason, we want to update the coupon store on the
Payola subscription.
We need to check whether the stripe_sub will `respond_to?(:discount)`
before attempting to copy the value because this attribute is added to
stripe-ruby-mock in version 2.2.0.

Maintain the active coupon code on a subscription

---

app/models/concerns/payola/plan.rb
spec/concerns/plan_spec.rb

Even if Stripe allows deleting a plan with subscriptions (and it will
keep the subscriptions), for referential integrity purposes in the
relational DB we shouldn't allow it. If you want to allow deleting a
plan then you should implement some variation of soft-deletes. I'm sure
that's what Stripe really does in the background so "deleting a plan"
actually just hides it.

Disallow deleting a plan if it has any related subscriptions

---

spec/models/payola/subscription_spec.rb

Just a syntax update to avoid noisy deprecation warning from RSpec.

Solve RSpec deprecation message by updating syntax

---

.gitignore
circle.yml
gemfiles/rails-4.1.gemfile
payola.gemspec

Specs are running (and passing) against Rails 4.1 and 4.2 on CI environment. This PR lays the groundwork to introduce Rails 5.0 testing+support in a subsequent PR.

Test Payola against Rails versions 4.1, 4.2

---

CHANGELOG.md
payola.gemspec

`TypeError: api_key must be a string` errors happen with certain version
combinations of stripe-ruby and stripe-ruby-mock. Certain versions of
stripe-ruby-mock seem to be the trigger (e.g. 2.1.0) used in combination
with more recent stripe-ruby versions (e.g. 1.55.0) that perform the
api_key-String check.

Fix api_key String spec errors with stripe-ruby-mock 2.3.1

---

CHANGELOG.md
app/assets/javascripts/payola/subscription_form_onestep.js

Current version relies on server-side validation only.
This PR adds client-side validation by using Stripe validation helpers, see https://stripe.com/docs/stripe.js?#card-validation-helpers

Add client side validation

---

lib/payola.rb
spec/models/payola/env_wrapper_spec.rb

Stripe started checking types on the API key at some point, which
means our `EnvWrapper` stopped being effective. This patch passes
the `is_a?` call through to the underlying ENV value.
Fixes #256

Ensure ENV keys are seen as strings

---

CHANGELOG.md
README.md
app/assets/javascripts/payola/checkout_button.js
app/assets/javascripts/payola/form.js
app/assets/javascripts/payola/subscription_checkout_button.js
app/assets/javascripts/payola/subscription_form_onestep.js
app/assets/javascripts/payola/subscription_form_register.js
app/assets/javascripts/payola/subscription_form_twostep.js
gemfiles/rails_4_1.gemfile
spec/services/payola/invoice_failed_spec.rb
spec/services/payola/invoice_paid_spec.rb

Scripts updated to use this approach:
``` js
// Use jQuery namespaced events to prevent duplicate handlers
var PayolaCheckout = {
initialize: function() {
$(document)
.off('click.payola-checkout-button') // remove any previous handler
.on('click.payola-checkout-button', '.payola-checkout-button',
function(e) { ... }
);
}
...
}
PayolaCheckout.initialize();
```
This approach has all of the following features, some of which have not been
available in any previous approaches:
- Works with or without Turbolinks
- Works with all Turbolinks versions without having to version-sniff
- No reference to the `Turbolinks` object
- Works with Payola forms and buttons that aren't inserted into the DOM until
after the document is ready
- Avoids accidental duplicate event handlers (say if developer …

[WIP] Support Turbolinks & non-Turbolinks apps reliably

---

app/assets/javascripts/payola/form.js
app/services/payola/create_sale.rb

Our product allows for multiple currency that is set at an individual charge level.  This change allows the form to override the currency with a custom form element data-payola-currency='usd'.

allow checkout form to override currency

---

app/models/payola/sale.rb
app/models/payola/subscription.rb
spec/dummy/config/initializers/new_framework_defaults.rb

This fixes #259 - with rails 5.1 this is now a breaking issue in upgrading from 5.0 -> 5.1.
Any belongs_to that didn't have presence validation already on the model now has optional: true & and the dummy app config default is enabled as well.
Hopefully I didn't miss anything...

set optional:true on all non-presence validated belongs_to associations

---

app/assets/javascripts/payola/form.js

This change grabs the stripe_customer_id and passes it to the buy route to allow finding the StripeCustomer if one already exists.

pass stripe_customer_id to buy route

---

CHANGELOG.md
app/controllers/payola/subscriptions_controller.rb
app/services/payola/change_subscription_plan.rb
app/views/payola/subscriptions/_change_plan.html.erb
spec/controllers/payola/subscriptions_controller_spec.rb
spec/services/payola/change_subscription_plan_spec.rb

When you update the subscription to a different plan with `trial_period_days` set, the plan's trial starts, resulting in an unwanted trial period. I've added the ability to set `trial_end`. Set `trial_end` to `now` if you don't want to use the trial.
> Unix timestamp representing the end of the trial period the customer will get before being charged for the first time. If set, trial_end will override the default trial period of the plan the customer is being subscribed to. The special value `now` can be provided to end the customer’s trial immediately.
> 
> https://stripe.com/docs/api#update_subscription-trial_end
> Stripe immediately attempts payment for these subscription changes:
> - From a subscription that doesn’t require payment (e.g., due to a trial, free plan, or coupon) to a paid …

Feature: Added trial_end and coupon to change_subscription_plan

---

CHANGELOG.md
app/services/payola/change_subscription_plan.rb
spec/services/payola/change_subscription_plan_spec.rb

When subscription plan changes, Stripe resets `cancel_at_period_end` (see https://stripe.com/docs/subscriptions/canceling-pausing#reactivating-canceled-subscriptions) but Payola doesn't do the same.
This pull request fixes that.

Reset subscription cancel_at_period_end on plan change

---

app/assets/javascripts/payola/subscription_form_onestep.js

This doesn't really cause much of an issue but it causes tests to fail when you're checking for Javascript errors.

Sometimes guid passed to the poll function is undefined

---

CHANGELOG.md
lib/payola.rb
payola.gemspec

Fixes an error being thrown when running `rails g payola:install` which was caused by an update to the `stripe_event` gem where `StripeEvent.event_retriever` was changed to `event_filter`. #335 
Tests were originally failing and are now passing, and the installation completed without an error. I didn't add any new tests as I assume the integration with the `stripe_event` gem is fully covered by the existing tests and that if this fix wasn't sufficient, tests would be failing.

#335 Payola.reset! uses StripeEvent.event_filter instead of event_retriever

---

app/views/payola/transactions/_stripe_header.html.erb

Added stripe.js version 3 to stripe header. Stripe js version 3 allows for the use of Stripe Elements for checkout forms.

Added stripe.js version 3 to stripe header
